# Generated by Django 3.2.12 on 2023-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_at', models.DateTimeField(null=True)),
                ('checkin_manager', models.CharField(max_length=255, null=True)),
                ('driver_name', models.CharField(max_length=255, null=True)),
                ('license_plate', models.CharField(max_length=255, null=True)),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('truck_number', models.CharField(max_length=255, null=True)),
                ('direct_cntr', models.CharField(max_length=255, null=True)),
                ('in_trailer', models.CharField(max_length=255, null=True)),
                ('seal_number', models.CharField(max_length=255, null=True)),
                ('checkout_at', models.DateTimeField(blank=True, null=True)),
                ('checkout_manager', models.CharField(max_length=255, null=True)),
                ('out_trailer', models.CharField(max_length=255, null=True)),
                ('load_status', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name_plural': 'Truck Tracking Data',
            },
        ),
    ]
