# Generated by Django 3.2.12 on 2023-08-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReinventData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program', models.CharField(max_length=100)),
                ('late_day', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_day', models.CharField(max_length=100)),
                ('remark', models.TextField(blank=True, max_length=76, null=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
